### ISSUE TITLE
The format of s2p

### ISSUE THREAD

**Issue by John-McCartney** [Maije2908/Fitting_Algorithm#3]
Should the s parameter contained in the s2p file be in DB or RI format? Does it affect calculations?

**Comment by John-McCartney** [comment]
The comments are so clear, and I really enjoy reading the code.

**Comment by andree-sc** [comment]
Hi, sorry to get back to you *this* late, we haven't done much dev work since quite some time

no, it is all handled via the scikit-rf lib, I think their TS reader is able to read pretty much any s2p format you throw at it. unsure abt mixed mode s-params, but have a look at https://scikit-rf.readthedocs.io/en/latest/

this is the library we mainly use :)

**Comment by John-McCartney** [comment]
> Hi, sorry to get back to you _this_ late, we haven't done much dev work since quite some time
> 
> no, it is all handled via the scikit-rf lib, I think their TS reader is able to read pretty much any s2p format you throw at it. unsure abt mixed mode s-params, but have a look at https://scikit-rf.readthedocs.io/en/latest/
> 
> this is the library we mainly use :)

Thanks for your reply. This project has helped me a lot！
